CREATE DATABASE pc1;
USE pc1;

CREATE TABLE usuarios(
 ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
 Usuario VARCHAR(100) NOT NULL,
 Pass VARCHAR(100) NOT NULL
);

INSERT INTO USUARIOS (Usuario, Pass) VALUES ('Junior', '342113');

SELECT * FROM usuarios